CREATE OR REPLACE PACKAGE EMPPACKAGE AS --SPECIFICATION
PROCEDURE INC_SALARY(E_NO NUMBER);
FUNCTION AVG_SALARY(E_NO NUMBER) RETURN VARCHAR2;
END EMPPACKAGE;

create or replace PACKAGE BODY EMPPACKAGE AS --BODY

PROCEDURE INC_SALARY(E_NO NUMBER) IS
BEGIN
UPDATE EMPLOYEE
SET EMPLOYEE.SALARY=EMPLOYEE.SALARY+10000
WHERE EMPLOYEE.EMPNO=E_NO;
END INC_SALARY;

FUNCTION AVG_SALARY(E_NO NUMBER)RETURN VARCHAR2
IS 
MSG VARCHAR2(20);
AVG_SALARY NUMBER;
EMP_RECORD EMPLOYEE%ROWTYPE;
BEGIN
SELECT AVG(SALARY) 
INTO AVG_SALARY
FROM EMPLOYEE;
DBMS_OUTPUT.PUT_LINE('AVG SALARY IS '||AVG_SALARY);
SELECT * 
INTO EMP_RECORD
FROM EMPLOYEE
WHERE EMPLOYEE.EMPNO=E_NO;
IF EMP_RECORD.SALARY>AVG_SALARY THEN MSG:='GREATER';
ELSE MSG:='LESS';
END IF;
RETURN MSG;
END AVG_SALARY;
END EMPPACKAGE;

SET SERVEROUTPUT ON
DECLARE
TEXT VARCHAR2(20);
NUM1 NUMBER;
BEGIN
NUM1:=&ENETR_NUM1;

EMPPACKAGE.INC_SALARY(NUM1);
TEXT:=EMPPACKAGE.AVG_SALARY(NUM1);
DBMS_OUTPUT.PUT_LINE(TEXT);
END;
